name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4

      - name: 📦 Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('flashcards-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 📥 Install Dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./flashcards-frontend

      - name: 🛠️ Build Angular Project
        run: npm run build
        working-directory: ./flashcards-frontend

      - name: 🚀 Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MCLEARN }}
          projectId: mclearn-d113a
          channelId: live
          entryPoint: flashcards-frontend  # 👉 hier wird der Pfad zur firebase.json gesetzt
